# Generated by Django 6.1.2 on 2026-10-07 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ORDER_RECEIVED', 'Order received'), ('ORDER_ACCEPTED', 'Order accepted'), ('ORDER_REJECTED', 'Order rejected'), ('ORDER_PREPARING', 'Order preparing'), ('ORDER_READY', 'Order ready'), ('ORDER_COMPLETED', 'Order completed'), ('ORDER_CANCELLED', 'Order cancelled'), ('DRIVER_ASSIGNED', 'Driver assigned'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('PAYMENT_SUCCESS', 'Payment success'), ('PAYMENT_FAILED', 'Payment failed'), ('LOW_STOCK', 'Low stock')], max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notification_user_read_idx')],
            },
        ),
    ]
