# Generated by Django 6.1.2 on 2026-10-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('TIGO_PESA', 'Tigo Pesa'), ('AIRTEL_MONEY', 'Airtel Money'), ('CARD', 'Card'), ('BANK', 'Bank'), ('CASH', 'Cash')], max_length=32)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=32)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('payment_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_status'], name='payment_status_idx')],
            },
        ),
    ]
